cluster/bootstrap.go:125: cannot use env (type *envInfo) as type Env in argument to GuaranteeSingleRun:  *envInfo does not implement Env (missing LocalIP method)